### ISSUE TITLE
How to handle optional input?

### ISSUE THREAD

**Issue by zhaoyao91** [Jackong/koa-input#1]
Thanks for your nice work!
I don't know how to handle optional input with this package.
I've tried a possible yet not very good way:

```
  r.post('/input',
  input('body', 'email',[null, undefined, v.isEmail]),
  function*() {
      this.body = this.request.body
  });
```

but it fails when the input doesn't contain 'email' at all.

**Comment by Jackong** [comment]
input with arguments:

``` js
input(source, name, pattern, default, error);
```

you can just pass a not-undefined default value to as optional input:

``` js
input('body', 'email', v.isEmail, null);
```

**Comment by zhaoyao91** [comment]
Do you mean if the client want to send a request without an optional value, it must set it to null, like this: `{email: null}` ? I don't think it's a good idea, usually, if you don't need some input, you just ignore it.

Otherwise, by this way, the server won't know if the client send an invalid input or didn't send the input (because it's optional) when it just receive a null in both cases.

**Comment by Jackong** [comment]
You are right.
If you just pass a not-undefined default value (null), your server will always get the default value (null) when the client send an invalid (or nothing) input.
But, in principle, the server should not allow any client to pass an invalid input that did not match the `pattern`.
In my opinion, the input naming as `email`, so it must be an email, otherwise, it can not be used by server.
But, if you want an multi-meaning `email`, i recommend:

``` js
input('body', 'xxx', v.isEmailOrOthers);
```

**Comment by zhaoyao91** [comment]
Ok, on the server side, default value pattern may work as well as optional value pattern. 

But on the client side, is it really necessary to force to send a null value if you don't need the input field? 

For example, to add a user without email, by what you mean, you must send `{name:'bob', email: null}`, but I think `{name: 'bob'}` is enough to pass the input check.

**Comment by Jackong** [comment]
validate with:

``` js
input('body', 'email', v.isEmail, null);
```

your client can send `{name: 'bob'}` without `email` field, your server will get `this.request.body.email === null`.

**Comment by zhaoyao91** [comment]
For the comment above: thanks, I have found this, so I've delete the question.

Well, the **default value pattern** may work as well as **optional value pattern**. I am trying to integrate this package into my project. Thanks :-)

**Comment by Jackong** [comment]
Well, let me know about any issues if you found.
